### ISSUE TITLE
⚠️Find lossless file saving format that supports EXIF tags

### ISSUE THREAD

**Issue by WebCoder49** [apollo-1845/2022-Plankton#12]

**Comment by WebCoder49** [comment]
* PNG unsupported by `exif`
* JPEG is lossy<sup><a href="https://en.wikipedia.org/wiki/JPEG">Wikipedia</a></sup>

**Comment by WebCoder49** [comment]
Tried PIL w/ PNG; doesn't seem to work.

https://gist.github.com/WebCoder49/0d54a3b1df9b55ced658dda81d570d3e

**Comment by WebCoder49** [comment]
https://projects.raspberrypi.org/en/projects/code-for-your-astro-pi-mission-space-lab-experiment/2 - available libraries

**Comment by llamax1** [comment]
@WebCoder49 
TIFF?
[https://en.wikipedia.org/wiki/Exif](https://en.wikipedia.org/wiki/Exif)
[https://en.wikipedia.org/wiki/TIFF](https://en.wikipedia.org/wiki/TIFF)

**Comment by sbottingota** [comment]
`PIL` seems to be able to read exif data but not write it without other (unsupported) libraries.

**Comment by WebCoder49** [comment]
> @WebCoder49 TIFF? https://en.wikipedia.org/wiki/Exif https://en.wikipedia.org/wiki/TIFF

https://stackoverflow.com/questions/71385332/replace-add-tiff-image-tags-using-pillow-from-one-file-to-another / https://www.itu.int/itudoc/itu-t/com16/tiff-fx/docs/tiff6.pdf
