### ISSUE TITLE
Code to get + save ISS location

### ISSUE THREAD

**Issue by WebCoder49** [apollo-1845/2022-Plankton#6]
* [Raspberry Pi Tutorial](https://projects.raspberrypi.org/en/projects/code-for-your-astro-pi-mission-space-lab-experiment/6)

**Comment by sbottingota** [comment]
Not sure why, but can't seem to get ISS from the orbit library. I'm instead following [this](https://projects.raspberrypi.org/en/projects/where-is-the-space-station/4) tutorial.

**Comment by WebCoder49** [comment]
@sbottingota , I think you need to run the code an Astro Pi RPi computer to get the ISS location for the competition; if you're doing this on the ISS I would suggest using the Raspberry Pi tutorial; if not you can use another library such as the one you are looking at.

**Comment by sbottingota** [comment]
Sorry for not doing this quicker. I wrote a program along the guidelines of the first tutorial [here](https://github.com/apollo-1845/2022-Plankton/commit/6a414a4d426a0e9458a04d51a41ac09b85f758f9), but as my computer can't seem to find `orbit.ISS` , I haven't tested it yet. 

P.S.
Right now it's just meant to get the ISS latetude, longitude and altitude and save them to `ISSPositions.json`, along with the value from `time.time()`  every 2 seconds, but going forward how should I save the data?

**Comment by WebCoder49** [comment]
We want something foolproof, so if Java is built-in it may be a good idea, but Raspberry Pi suggests more compact csv files / png images with metadata.

**Comment by sbottingota** [comment]
Sorry, I don't really understand. Please could you clarify?

**Comment by WebCoder49** [comment]
I meant:
We are not completely sure about the format for now. Your use of JSON may be a good setup, but [this Raspberry Pi tutorial suggests its own more data-saving setup](https://projects.raspberrypi.org/en/projects/code-for-your-astro-pi-mission-space-lab-experiment/4).

**Comment by sbottingota** [comment]
I have modified the program to save the ISS position to a `.csv` file: [here](https://github.com/apollo-1845/2022-Plankton/commit/61bb76759b0fbb3f84fa141c111dc1a61caf99df)

 However, at the moment it saves all of the data with the index 0, and at the moment I'm not really sure how to fix that, but I'm working on it.

**Comment by WebCoder49** [comment]
I hope you are enjoying the weekend.
It appears that you are using `pandas` but I am not sure whether that is installed on the Astro Pi computer. I would suggest using manual code and file opening method "a" (append) as you will not need to edit existing entries, or use the built-in `csv` library as shown here. https://projects.raspberrypi.org/en/projects/code-for-your-astro-pi-mission-space-lab-experiment/10

**Comment by sbottingota** [comment]
Sorry, I didn't realise. I have changed that [here](https://github.com/apollo-1845/2022-Plankton/commit/4c85f9de3e1a6be4f114fbfe7e83e44ebfb9b7fa).
